variable "region" {}
variable "profile" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "azs" {}
variable "public_subnets" {}
variable "ipv6_subnets" {}
variable "environment" {}
variable "bastion_admins" {}
variable "pub_key" {}